package:
    name: seguid_calculator
    version: {{ environ.get('GIT_DESCRIBE_TAG', 'default') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  include_recipe: False
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
        - seguid_calculator = seguid_calculator.calculator:main
  osx_is_app: True

source:
  git_url: .

requirements:
    build:
        - python {{ python }}
        - setuptools
        - setuptools_scm
        - pytest-runner
    run:
        - python {{ python }}
        - wxpython
test:
  requires:
    - pytest
  imports:
    - seguid_calculator
  source_files:
    - tests
    - src
    - src/seguid_calculator

app:
    entry: seguid_calculator
    icon: calculator.png
    summary:  "Calculator for seguid checksums"
    own_environment: False

about:
  home: https://github.com/BjornFJohansson/seguid_calculator
  summary: A small GUI  for calculating SEGUID, lSEGUID and cSEGUID checksums for biological sequences
  license_file: LICENSE.txt
  license: BSD-3-Clause
  license_family: BSD

extra:
  maintainers:
   - "Björn Johansson <bjorn_johansson@bio.uminho.pt>"
