sudo: required
language: python
python:
- '2.7'
before_install:
- pip install --upgrade pip
- sudo add-apt-repository ppa:ubuntu-wine/ppa -y
- sudo apt-get update -qq
- sudo apt-get install -qq wine
- wget https://www.python.org/ftp/python/2.7.9/python-2.7.9.amd64.msi --output-document=python.msi
- wine msiexec /i python.msi /qn
- wine c:\\Python27\\python.exe -m pip install pywin32-219-cp27-none-win_amd64.whl
- wine c:\\Python27\\python.exe ~/.wine/drive_c/Python27/Scripts/pywin32_postinstall.py
  -install
- wine c:\\Python27\\python.exe -m pip install pyinstaller
- wget http://downloads.sourceforge.net/wxpython/wxPython3.0-win64-3.0.2.0-py27.exe
  --output-document=wxpython.exe
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wine wxpython.exe /sp- /verysilent /norestart /SUPPRESSMSGBOXES
- wine c:\\Python27\\Scripts\\pyinstaller --noconsole --icon=calc.ico --onefile seguid_calculator/seguid.py
install:
- pip install -e .
script:
- nosetests -v -w tests
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: b/FLCiwaTt+egDwahvIDRqnAZ3KtXPBOSfNiQSKaGNKsU4dmG5dZpLKOVVeBTSC1mz/F1kxfu/JFfzboBwcHG+h9G4/EDhy3CGKhcK5RZNF1NihrHexSu0UpXSAj59aTa1i9e7DAsECUQROMCRW0W1x4zxEm5ubZXR9aKBPlvO8=
  file: dist/seguid.exe
  on:
    tags: true
    all_branches: true
    repo: BjornFJohansson/seguid_calculator






















