language: objective-c
python:
- '2.7'
before_install:
- which python
- brew install python --universal --framework
- brew install wget
- which python
- export VERSIONER_PYTHON_PREFER_32_BIT=yes
- defaults write com.apple.versioner.python Prefer-32-Bit -bool yes
- which python
- python --version
- mkdir dl
- cd dl
- wget http://downloads.sourceforge.net/wxpython/wxPython3.0-osx-3.0.2.0-cocoa-py2.7.dmg
- ls
- cd ..
- sudo ./packages.sh
- arch -i386 python -c "import wx; print wx.__version__"
- arch -i386 pip install pyinstaller
- arch -i386 pyinstaller --noconsole --onefile --icon=calc.ico seguid_calculator/seguid.py
- ls
- hdiutil create dist/seguid.dmg -srcfolder dist/ -ov
- zip -r dist/seguid.zip dist/seguid.app
- ls dist/
install: true
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: MF00EsmiZujwu3DeuH4aijaADvdnZGW1Hkocs1es+ut8aFMEdTRDDUrTSJqTRef+JF5c2Ye56NafRZqU00aXmXevbOiTWMZd9mLmoDa12btri1mQFqFTMthv4guS+qS+qfZrSxfG+d/gKUHQDWXr49H9LoRqZtqWDrJpufavJC4=
  file:
    - "dist/seguid.dmg"
    - "dist/seguid.zip"
    - "dist/hw"
  on:
    tags: true
    all_branches: true
    repo: BjornFJohansson/seguid_calculator

