sudo: required
language: python
python:
  - "2.7"
before_install:
  - pip install --upgrade pip
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq wine
  - wget https://www.python.org/ftp/python/2.7.9/python-2.7.9.amd64.msi --output-document=python.msi
  - wine msiexec /i python.msi /qn
  - wget http://downloads.sourceforge.net/wxpython/wxPython3.0-win64-3.0.2.0-py27.exe --output-document=wxpython.exe
  - wine wxpython.exe /VERYSILENT
  - wine python -m pip install pywin32-219-cp27-none-win_amd64.whl
  - wine python Scripts\pywin32_postinstall.py -install
  - wine python ~/.wine/drive_c/Python27/Scripts/pywin32_postinstall.py -install
  - wine python -m pip install pyinstaller
  - wine pyinstaller --noconsole --icon=calc.ico --onefile seguid_calculator/seguid.py
install:
  - pip install -e .
script:

#!/bin/bash
#pyinstaller --noconsole --icon=calc.ico --onefile ./seguid_calculator/seguid.py
#read -p "Press [Enter] key..."

#!/bin/bash
#wine C:/Python27/python.exe pyinstaller/pyinstaller.py --noconsole --icon=calc.ico --onefile SEGUID_calculator_current.py
#read -p "Press [Enter] key..."



# - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
# - sudo apt-get update -qq
# - sudo apt-get install -qq wine1.7
# - wget http://repo.continuum.io/miniconda/Miniconda-latest-Windows-x86_64.exe
# - wine Miniconda-latest-Windows-x86_64.exe /S
#wine msiexec /i python-2.7.9.amd64.msi /qn
# - wget https://www.python.org/ftp/python/2.7.9/python-2.7.9.amd64.msi
# wget https://www.python.org/ftp/python/2.7.9/python-2.7.9.msi
# http://docs.travis-ci.com/user/build-configuration/
# - wget https://www.python.org/ftp/python/2.7.9/python-2.7.9.msi
#  - wget http://sourceforge.net/projects/pywin32/files/pywin32/Build%20219/pywin32-219.win-amd64-py2.7.exe/download --output-document=pywin32.exe
# Miniconda-3.7.3-Windows-x86_64.exe /InstallationType=AllUsers /RegisterPython=0 /S /D=C:\Program Files\Miniconda3
