language: python
python:
  - "2.7"
install:
  - pip install -e .
before_script:
  - sudo apt-get install -y python-wxgtk3.0
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coveralls
