sudo: required
language: python
python:
  - "2.7"
before_install:
  - pip install --upgrade pip
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-wxgtk2.8 wine
install:
  - pip install -e .
