sudo: required
language: python
python:
  - "2.7"
before_install:
  - pip install --upgrade pip
  - sudo apt-get update -qq
  - sudo apt-get install -qq wine
  - 
install:
  - pip install -e .
script:

# - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
# - sudo apt-get update -qq
# - sudo apt-get install -qq wine
# - wget https://www.python.org/ftp/python/2.7.9/python-2.7.9.msi


# http://docs.travis-ci.com/user/build-configuration/


#sudo: required
#language: python
#python:
#  - "2.7"
#before_install:
#  - pip install --upgrade pip
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq python-wxgtk2.8 wine
#install:
#  - pip install -e .
