language: objective-c
sudo: false
cache:
 - wget
 - pip
 - brew
 - conda
script:
 - bash ci.sh
deploy:
  - provider: releases
    draft: true
    skip_cleanup: true
    api_key:
      secure: dSK2zOaGfKqo33Ov5mlEv4H1tMsEo6eurhsLkgOWzfA/vB9uBfSJE7rokG5QTrb6Wsc8Dmeqq3rXZMRM1ArblyXkxlKuN0WuJSmJSkEE6DX37YJmWOQzP+xwXN/aQNCDGuv8jYlSbRxmFZX3k9bw9Ylh8/oJi08sC9iyrEy/QbI=
    file:
      - "dist/seguid_calculator.dmg"
      - "dist/seguid_calculator.zip"
      - "dist/seguid_calculator"
    on:
      tags: true
      branch: master
  - provider: script
    skip_cleanup: true
    script: python deploy_to_dropbox.py
    on:
      tags: false
      branch: master
notifications:
  email: false
