[tool.poetry]
name = "seguid-calculator2"
version = "2.0.0a1"
description = "hejhej"
authors = ["BjornFJohansson <bjornjobb@gmail.com>"]
license = "BSD"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10,<3.12"
wxPython = "^4.0.0"
seguid = "^0.0.1.post9004"



[tool.poetry-dynamic-versioning]
enable = true
[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
