
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.0-94-g6688a0c-dirty'
version_full = '6688a0ce7bbf6a3925eb3f380087ddb662992bf2-dirty'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

