
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.0.0-8-g31ac90a-dirty'
version_full = '31ac90a29ba803e67f0f5a382e6569ea1eaecf10-dirty'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

