
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-10-06T10:50:44+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "c35dc9c9d52b0aae83ca0d09fed7c43db6985d2d",
 "version": "1.0.0+0.gc35dc9c.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
