# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.28.dev0+g2df2eb5.d20230609'
__version_tuple__ = version_tuple = (1, 28, 'dev0', 'g2df2eb5.d20230609')
