name: Conda Build
on:
  release:
    types: [published]
jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.9", "3.8", "3.7", "3.6"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('environment-ci.yml') }}
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: seguid_build_environment
          python-version: ${{ matrix.python-version }}
          environment-file: seguid_build_environment.yml
      - name: conda info
        shell: bash -l {0}
        run: conda info --all
      - name: tags
        shell: bash -l {0}
        run: git tag
      - name: Build pypi wheel package
        shell: bash -l {0}
        run: python setup.py build bdist_wheel
      - name: conda config
        shell: bash -l {0}
        run: conda config --set anaconda_upload yes
      - name: Build conda package
        shell: bash -l {0}
        run: conda build --python ${{ matrix.python-version }} --no-include-recipe --dirty --token ${{ secrets.ANACONDATOKEN }} .




      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          skip_existing: true
