name: Pyinstaller
on:
  release:
    types: [published]
jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('environment-ci.yml') }}
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: seguid_build_environment
          python-version: ${{ matrix.python-version }}
          environment-file: seguid_build_environment.yml

      - name: conda info
        shell: bash -l {0}
        run: conda info --all

      - name: conda list
        shell: bash -l {0}
        run: conda list

      - name: Pyinstaller
        shell: bash -l {0}
        run: pyinstaller --onefile --windowed --icon=calc.ico --name seguid-calculator src/gui.py

      - name: ls
        shell: bash -l {0}
        run: ls dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/seguid-calculator.*
