name: Pypi Package
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    name: Pypi (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:

      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout
        uses: actions/checkout@v3

      - name: 🌍 Install conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: pypi_env.yml
          environment-name: pypi_env
          extra-specs: python=${{ matrix.python-version }}
          cache-downloads: true
          cache-env: true

      - name: 🐍 micromamba info
        shell: bash -l {0}
        run: micromamba info

      - name: 🐍 micromamba list
        shell: bash -l {0}
        run: micromamba list

      - name: Build pypi source dist and wheel package
        shell: bash -l {0}
        run: python setup.py build sdist bdist_wheel

      - name: Publish a Python distribution to PyPI
        if: matrix.os == 'ubuntu-latest'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.SEGUID_CALCULATOR_TOKEN }}
          skip_existing: true
