name: Pytest
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
jobs:
  build:
    name: Pytest (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.10", "3.9", "3.8", "3.7"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('environment-ci.yml') }}
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: seguid_calculator_build_environment
          python-version: ${{ matrix.python-version }}
          environment-file: seguid_calculator_build_environment.yml

      - name: conda info
        shell: bash -l {0}
        run: conda info --all

      - name: conda list
        shell: bash -l {0}
        run: conda list

      - name: Install from source
        shell: bash -l {0}
        run: pip install --editable . --no-deps

      - name: set PY_IGNORE_IMPORTMISMATCH=1
        uses: allenevans/set-env@v2.0.0
        with:
          PY_IGNORE_IMPORTMISMATCH: '1'

      - name: python run_test.py
        shell: bash -l {0}
        run: python run_test.py
