name: Pytest
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request: {}
  workflow_dispatch:
jobs:
  build:
    name: Pytest (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.11", "3.10", "3.9", "3.8"]
    runs-on: ${{ matrix.os }}
    steps:

      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout
        uses: actions/checkout@v3

      - name: 🌍 Install conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: test_env.yml
          environment-name: test_env
          extra-specs: python=${{ matrix.python-version }}
          cache-downloads: true
          cache-env: true

      - name: 🐍 micromamba info
        shell: bash -l {0}
        run: micromamba info

      - name: 🐍 micromamba list
        shell: bash -l {0}
        run: micromamba list

      - name: Install from source
        shell: bash -l {0}
        run: pip install --editable . --no-deps

      - name: set PY_IGNORE_IMPORTMISMATCH=1
        uses: allenevans/set-env@v2.0.0
        with:
          PY_IGNORE_IMPORTMISMATCH: '1'

      - name: python run_test.py
        shell: bash -l {0}
        run: python run_test.py
